spring:
  application:
    name: sign_connect
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sign_connect
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
